# Generated by Django 5.1.4 on 2026-06-08 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador URL')),
                ('intro_text', models.TextField(blank=True, verbose_name='Introducción para el entrevistado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text="Identificador estable opcional (p.ej. 'q1').", verbose_name='Código')),
                ('text', models.TextField(verbose_name='Pregunta')),
                ('help_text', models.TextField(blank=True, help_text="Texto gris de ayuda (las pistas 'Profundizar').", verbose_name='Ayuda')),
                ('type', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('single_choice', 'Opción única'), ('multi_choice', 'Opción múltiple'), ('scale', 'Escala')], default='textarea', max_length=20, verbose_name='Tipo')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.block')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['block__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Opción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('perfil', models.CharField(blank=True, max_length=200, verbose_name='Perfil / cargo')),
                ('edad', models.CharField(blank=True, max_length=20, verbose_name='Edad aproximada')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentimiento')),
                ('priority', models.CharField(blank=True, choices=[('appearance', 'Verse joven y sano'), ('longevity', 'Vivir más años'), ('mind', 'Claridad mental y productividad')], max_length=20, verbose_name='Prioridad principal')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completada')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Avance (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('notes_copy', models.TextField(blank=True, verbose_name='Frases para copy')),
                ('notes_insight', models.TextField(blank=True, verbose_name='Insight central')),
                ('notes_offer', models.TextField(blank=True, verbose_name='Hipótesis de oferta')),
                ('notes_final', models.TextField(blank=True, verbose_name='Notas finales')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_snapshot', models.TextField(blank=True)),
                ('value_text', models.TextField(blank=True, verbose_name='Respuesta (texto)')),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='Opciones elegidas')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.submission')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
