# Generated by Django 5.1.4 on 2026-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='submission',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes_motivadores',
            field=models.TextField(blank=True, verbose_name='Motivadores principales'),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes_objeciones',
            field=models.TextField(blank=True, verbose_name='Objeciones detectadas'),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes_prioridad',
            field=models.CharField(blank=True, max_length=120, verbose_name='Prioridad dominante identificada'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='edad',
            field=models.CharField(blank=True, max_length=20, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes_copy',
            field=models.TextField(blank=True, verbose_name='Frases textuales importantes'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes_final',
            field=models.TextField(blank=True, verbose_name='Observaciones finales'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes_insight',
            field=models.TextField(blank=True, verbose_name='Insight principal'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes_offer',
            field=models.TextField(blank=True, verbose_name='Hipótesis de oferta para este perfil'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='perfil',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profesión / cargo'),
        ),
    ]
